CREATE DATABASE banking_db;

GO

USE banking_db;

--—Œ«ƒ¿Õ»≈ “¿¡À»÷ ¡ƒ--------------------------------------------------------

CREATE TABLE Banks
(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	BankName VARCHAR(30) NOT NULL
)

CREATE TABLE Localities
(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	LocalityName VARCHAR(30) NOT NULL
)

CREATE TABLE BankBranches
(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	LocalAddress VARCHAR(30) NOT NULL,
	BankId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Banks(ID),
	LocalityId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Localities(ID)
)

CREATE TABLE SocialStatuses
(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	StatusName VARCHAR(30) NOT NULL
)

CREATE TABLE Persons
(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	PersonName VARCHAR(30) NOT NULL,
	StatusId UNIQUEIDENTIFIER NOT NULL UNIQUE FOREIGN KEY REFERENCES SocialStatuses(ID) 
)

CREATE TABLE Accounts
(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	UserName VARCHAR(30) NOT NULL,
	AccountMoney MONEY DEFAULT 0,
	BankId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Banks(ID),
	PersonId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES persons(ID)
)

CREATE TABLE Cards
(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	CardName VARCHAR(30) NOT NULL,
	CardMoney MONEY DEFAULT 0,
	AccountId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Accounts(ID) 
)
